#!/usr/bin/env bash
# Install nginx web server
sudo apt update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
