#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt -y update
sudo apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=hdZUCjAQaGw permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
